openapi: 3.0.3
info:
  title: Custom Shop API
  description: "An API for managing a shop of customizable products."
  version: 1.0.0
  contact:
    name: API Support
    email: karolni90@gmail.com

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /admin/product-types:
    post:
      summary: Create a new product type
      description: Creates a product type along with its attributes and options.
      operationId: createProductType
      tags:
        - Admin - Product Types
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductTypeRequest"
      responses:
        "201":
          description: Product type created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductTypeResponse"
        "400":
          description: Bad request - Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          $ref: "#/components/responses/InternalServerError"
    get:
      summary: Get list of existing product types
      description: Returns a list of all existing product types with their ID, name, and configuration.
      operationId: getProductTypes
      tags:
        - Admin - Product Types
      responses:
        "200":
          description: Successfully retrieved the list of product types.
          content:
            application/json:
              schema:
                type: object
                properties:
                  productTypes:
                    type: array
                    items:
                      $ref: "#/components/schemas/ProductTypeItemResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /admin/product-types/attributes:
    post:
      summary: Add attributes to an existing product type
      description: >
        Adds one or more attributes (with possible options) to an existing product type. 
        Only allowed if the product type is fully customizable.
      operationId: addAttributesToProductType
      tags:
        - Admin - Product Types
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddAttributesRequest"
      responses:
        "200":
          description: Attributes added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Attributes added successfully"
        "400":
          description: Bad request - Cannot add attributes to a non-fully-customizable product type or invalid data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /admin/product-types/not-allowed-combinations:
    post:
      summary: Add not allowed combinations to a product type
      description: >
        Defines not allowed attribute-option combinations for a customizable product type. 
        Only applicable if the product type is fully customizable.
      operationId: addNotAllowedCombinations
      tags:
        - Admin - Product Types
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotAllowedCombinationsRequest"
      responses:
        "200":
          description: Not allowed combinations added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Not allowed combinations added successfully"
        "400":
          description: Bad request - Cannot add restrictions to a non-customizable product type or invalid data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /admin/product-types/{productTypeId}:
    get:
      summary: Get product type details
      description: Returns detailed information about a specific product type, including its attributes, options, and not-allowed combinations.
      operationId: getProductTypeDetails
      tags:
        - Admin - Product Types
      parameters:
        - name: productTypeId
          in: path
          required: true
          description: The unique identifier of the product type.
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        "200":
          description: Successfully retrieved product type details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductTypeDetailsResponse"
        "404":
          description: Product type not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    ProductTypeRequest:
      type: object
      required:
        - name
        - config
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 255
          example: "Bicycle"
        config:
          $ref: "#/components/schemas/ProductTypeRequestConfig"

    ProductTypeRequestConfig:
      type: object
      description: "config object for a product type."
      required:
        - customisation
      properties:
        customisation:
          type: string
          example: "fully_customizable"

    ProductTypeItemResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the product type.
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          description: Name of the product type.
          example: "Bicycle"
        config:
          type: object
          properties:
            customisation:
              type: string
              description: Defines whether the product type is customizable.
              example: "fully_customizable"

    AddAttributesRequest:
      type: object
      required:
        - productTypeID
        - attributes
      properties:
        productTypeID:
          type: string
          example: 1
        attributes:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/AttributeRequest"
      example:
        productTypeID: 1
        attributes:
          - attributeName: "Frame Finish"
            possibleOptions: [ "Matte", "Shiny" ]
          - attributeName: "Wheels"
            possibleOptions: [ "Road Wheels", "Cruiser Wheels" ]

    AttributeRequest:
      type: object
      required:
        - attributeName
        - possibleOptions
      properties:
        attributeName:
          type: string
          minLength: 3
          maxLength: 100
          example: "Frame Type"
        possibleOptions:
          type: array
          minItems: 1
          items:
            type: string
          example: [ "Matte", "Shiny" ]

    ProductTypeResponse:
      type: object
      properties:
        message:
          type: string
          example: "Product type created successfully"
        productTypeId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        attributes:
          type: array
          items:
            $ref: "#/components/schemas/AttributeResponse"

    AttributeResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Frame Type"
        options:
          type: array
          items:
            type: string
          example: ["Full-suspension", "Diamond", "Step-through"]

    NotAllowedCombinationsRequest:
      type: object
      required:
        - productTypeId
        - notAllowedCombinations
      properties:
        productTypeId:
          type: string
          example: 1
        notAllowedCombinations:
          type: array
          minItems: 1
          items:
            type: array
            minItems: 2
            items:
              $ref: "#/components/schemas/NotAllowedCombinationItem"
      example:
        productTypeId: 1
        notAllowedCombinations:
          - - attributeId: 101
              attributeOptionId: 1001
            - attributeId: 102
              attributeOptionId: 2002
          - - attributeId: 103
              attributeOptionId: 3003
            - attributeId: 104
              attributeOptionId: 4004
            - attributeId: 105
              attributeOptionId: 5005

    NotAllowedCombinationItem:
      type: object
      required:
        - attributeId
        - attributeOptionId
      properties:
        attributeId:
          type: integer
          format: int64
          example: 101
        attributeOptionId:
          type: integer
          format: int64
          example: 1001
    ProductTypeDetailsResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the product type.
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          description: Name of the product type.
          example: "Bicycle"
        config:
          type: object
          properties:
            customization:
              type: string
              description: Defines whether the product type is customizable.
              example: "fully_customizable"
        attributes:
          type: array
          description: List of attributes associated with the product type.
          items:
            $ref: "#/components/schemas/ProductAttribute"
        not_allowed_combinations:
          type: array
          description: List of not-allowed combinations for this product type.
          items:
            $ref: "#/components/schemas/NotAllowedCombinationR"

    ProductAttribute:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier of the attribute.
          example: 1
        name:
          type: string
          description: Name of the attribute.
          example: "Frame Finish"
        options:
          type: array
          description: List of available options for this attribute.
          items:
            $ref: "#/components/schemas/AttributeOption"

    AttributeOption:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier of the attribute option.
          example: 101
        name:
          type: string
          description: Name of the option.
          example: "Matte"

    NotAllowedCombinationR:
      type: object
      properties:
        combination_id:
          type: integer
          format: int64
          description: Unique identifier of the not-allowed combination.
          example: 9001
        options:
          type: array
          description: List of options that form a not-allowed combination.
          items:
            $ref: "#/components/schemas/AttributeOption"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Invalid request parameters"

  responses:
    NotFound:
      description: "Resource not found"
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Resource not found"
      headers:
        Content-Type:
          description: "The content type of the response"
          schema:
            type: string
            example: "application/json"

    InternalServerError:
      description: "Internal server error"
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "An unexpected error occurred"
      headers:
        Content-Type:
          description: "The content type of the response"
          schema:
            type: string
            example: "application/json"
