openapi: 3.0.3
info:
  title: Custom Shop API
  description: "An API for managing a shop of customizable products."
  version: 1.0.0
  contact:
    name: API Support
    email: karolni90@gmail.com

servers:
  - url: http://localhost:8080/api
    description: Local development server

paths:
  /admin/product-types:
    post:
      summary: Create a new product type
      description: Creates a product type along with its attributes and options.
      operationId: createProductType
      tags:
        - Admin - Product Types
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductTypeRequest"
      responses:
        "201":
          description: Product type created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductTypeResponse"
        "400":
          description: Bad request - Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /admin/product-types/attributes:
    post:
      summary: Add attributes to an existing product type
      description: >
        Adds one or more attributes (with possible options) to an existing product type. 
        Only allowed if the product type is fully customisable.
      operationId: addAttributesToProductType
      tags:
        - Admin - Product Types
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddAttributesRequest"
      responses:
        "200":
          description: Attributes added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Attributes added successfully"
        "400":
          description: Bad request - Cannot add attributes to a non-fully-customisable product type or invalid data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    ProductTypeRequest:
      type: object
      required:
        - name
        - config
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 255
          example: "Bicycle"
        config:
          $ref: "#/components/schemas/ProductTypeRequestConfig"

    ProductTypeRequestConfig:
      type: object
      description: "config object for a product type."
      required:
        - customisation
      properties:
        customisation:
          type: string
          example: "fullyCustomisable"

    AddAttributesRequest:
      type: object
      required:
        - productTypeID
        - attributes
      properties:
        productTypeID:
          type: string
          example: 1
        attributes:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/AttributeRequest"
      example:
        productTypeID: 1
        attributes:
          - attributeName: "Frame Finish"
            possibleOptions: [ "Matte", "Shiny" ]
          - attributeName: "Wheels"
            possibleOptions: [ "Road Wheels", "Cruiser Wheels" ]

    AttributeRequest:
      type: object
      required:
        - attributeName
        - possibleOptions
      properties:
        attributeName:
          type: string
          minLength: 3
          maxLength: 100
          example: "Frame Type"
        possibleOptions:
          type: array
          minItems: 1
          items:
            type: string
          example: [ "Matte", "Shiny" ]

    ProductTypeResponse:
      type: object
      properties:
        message:
          type: string
          example: "Product type created successfully"
        productTypeId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        attributes:
          type: array
          items:
            $ref: "#/components/schemas/AttributeResponse"

    AttributeResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Frame Type"
        options:
          type: array
          items:
            type: string
          example: ["Full-suspension", "Diamond", "Step-through"]

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Invalid request parameters"

  responses:
    NotFound:
      description: "Resource not found"
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Resource not found"
      headers:
        Content-Type:
          description: "The content type of the response"
          schema:
            type: string
            example: "application/json"

    InternalServerError:
      description: "Internal server error"
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "An unexpected error occurred"
      headers:
        Content-Type:
          description: "The content type of the response"
          schema:
            type: string
            example: "application/json"
